backend:
  name: git-gateway
  branch: master

media_folder: "public/images"
public_folder: "/images"

collections:
    ##
    # Paintings
    ##
  - name: "piece"
    label: "Maleri"
    folder: "src/content/pieces/"
    create: true
    slug: "{{slug}}"
    format: "json"
    fields:
      ## Basic information ##
      - {label: "Stykkets navn ( unikt )", name: "title", widget: "string"}
      - {label: "Beskrivelse", name: "description", widget: "markdown"}
      - {label: "Billede ( bliver vist i galleriet )", name: "display_image", widget: "image"}
      - {label: "Billeder", name: "images", widget: "list", fields: [
          {label: "Billede", name: "image", widget: "image"}
      ]}

    ##
    # pages
    ##
  - name: "pages"
    label: "Sider"
    files:
      ###
      ### Contact
      ###
      - file: "src/content/contact.json"
        format: "json"
        name: "contact"
        label: "Kontakt"
        fields:
          - {label: "Titel", name: "title", widget: "string"}
          - {label: "Titel billede", name: "titleImage", widget: "image"}

